# Operations

In [9]:
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
from functools import reduce


def ndarray_to_str(t: np.ndarray):
    s = '\n{} (shape={}, dtype={})'.format(t, t.shape, t.dtype)
    s = s.replace('\n', '\n{}'.format(' ' * 2))
    return s

def make_array_by_shape(shape, inital=1):
    m = reduce(lambda x, y: x * y, shape)
    print(m)
    return np.reshape(np.arange(inital, m + inital), shape)

## 1. Arithmetic operator

### 1.1 Scalar operation

In [ ]:
a = 10
b = 0.1

#### 1.1.1. $m+n$

In [ ]:
r = np.add(a, b)
print('* when a={}, b={}, then "np.add(a, b)" is {}'.format(a, b, r))

#### 1.1.2. $m-n$

In [ ]:
r = np.subtract(a, b)
print('* when a={}, b={}, then "np.subtract(a, b)" is {}'.format(a, b, r))

#### 1.1.3. $m*n$

In [ ]:
r = np.multiply(a, b)
print('* when a={}, b={}, then "np.multiply(a, b)" is {}'.format(a, b, r))

#### 1.1.4. $m÷n$

In [ ]:
r = np.subtract(a, b)
print('* when a={}, b={}, then "np.subtract(a, b)" is {}'.format(a, b, r))

#### 1.1.5. $m\%n$

In [ ]:
r = np.mod(a, b)
print('* when a={}, b={}, then "np.mod(a, b)" is {}'.format(a, b, r))

### 1.2. Tensor and scalar operations

In [ ]:
a = [[1, 2, 3], [4, 5, 6]]
b = 2.

#### 1.2.1. $T(x, y) + n$

In [ ]:
r = np.add(a, b)
print('* when a={}, b={}, then "np.add(a, b)" is: {}'.format(a, b, ndarray_to_str(r)))

#### 1.2.2. $T(x, y) - n$

In [ ]:
r = np.subtract(a, b)
print('* when a={}, b={}, then "np.subtract(a, b)" is: {}'.format(a, b, ndarray_to_str(r)))

#### 1.2.3. $T(x, y)*n$

In [ ]:
r = np.multiply(a, b)
print('* when a={}, b={}, then "np.multiply(a, b)" is: {}'.format(a, b, ndarray_to_str(r)))

#### 1.2.4. $T(x, y)÷n$

In [ ]:
r = np.divide(a, b)
print('* when a={}, b={}, then "np.divide(a, b)" is: {}'.format(a, b, ndarray_to_str(r)))

#### 1.2.5. $T(x, y)\%n$

In [ ]:
r = np.mod(a, b)
print('* when a={}, b={}, then "np.mod(a, b)" is: {}'.format(a, b, ndarray_to_str(r)))

### 1.3. Tensor and vector operations

In [ ]:
a = [[1, 2, 3], [4, 5, 6]]
b = [0.1, 0.2, 0.3]

#### 1.3.1. $T_1(x_1, y_1) + T_2(x_2)$

In [ ]:
r = np.add(a, b)
print('* when a={}, b={}, then "np.add(a, b)" is: {}'.format(a, b, ndarray_to_str(r)))

#### 1.3.2. $T_1(x_1, y_1) - T_2(x_2)$

In [ ]:
r = np.subtract(a, b)
print('* when a={}, b={}, then "np.subtract(a, b)" is: {}'.format(a, b, ndarray_to_str(r)))

#### 1.3.3. $T_1(x_1, y_1) * T_2(x_2)$

In [ ]:
r = np.multiply(a, b)
print('* when a={}, b={}, then "np.multiply(a, b)" is: {}'.format(a, b, ndarray_to_str(r)))

#### 1.3.4. $T_1(x_1, y_1) ÷ T_2(x_2)$

In [ ]:
r = np.divide(a, b)
print('* when a={}, b={}, then "np.divide(a, b)" is: {}'.format(a, b, ndarray_to_str(r)))

#### 1.3.5. $T_1(x_1, y_1) \% T_2(x_2)$

In [ ]:
r = np.mod(a, b)
print('* when a={}, b={}, then "np.mod(a, b)" is: {}'.format(ndarray_to_str(r)))

### 1.4. Tensors and tensor operations

In [ ]:
a = [[1, 2, 3], [4, 5, 6]]
b = [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]

#### 1.4.1. $T_1(x_1, y_1) + T_2(x_2, y_2)$

In [ ]:
r = np.add(a, b)
print('* when a={}, b={}, then "np.add(a, b)" is: {}'.format(a, b, ndarray_to_str(r)))

#### 1.4.2. $T_1(x_1, y_1) - T_2(x_2, y_2)$

In [ ]:
r = np.subtract(a, b)
print('* when a={}, b={}, then "np.subtract(a, b)" is {}'.format(a, b, ndarray_to_str(r)))

#### 1.4.1. $T_1(x_1, y_1) * T_2(x_2, y_2)$

In [ ]:
r = np.multiply(a, b)
print('* when a={}, b={}, then "np.multiply(a, b)" is {}'.format(a, b, ndarray_to_str(r)))

#### 1.4.1. $T_1(x_1, y_1) ÷ T_2(x_2, y_2)$

In [ ]:
r = np.divide(a, b)
print('* when a={}, b={}, then "np.divide(a, b)" is {}'.format(a, b, ndarray_to_str(r)))

#### 1.4.1. $T_1(x_1, y_1) \% T_2(x_2, y_2)$

In [ ]:
r = np.mod(a, b)
print('* when a={}, b={}, then "np.mod(a, b)" is {}'.format(a,b,ndarray_to_str(r)))

### 1.5. Operator overriade

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
print('* when a is {}\n and b is {}'.format(ndarray_to_str(a), ndarray_to_str(b)))

r = a + b
print('\n* then "a + b" is {}'.format(ndarray_to_str(r)))

r = a - b
print('  and "a - b" is {}'.format(ndarray_to_str(r)))

r = a * b
print('  and "a * b" is {}'.format(ndarray_to_str(r)))

r = a / b
print('  and "a / b" is {}'.format(ndarray_to_str(r)))

r = a % b
print('  and "a % b" is {}'.format(ndarray_to_str(r)))

## 2. Broadcast

In [11]:
from itertools import repeat

shape = (4, 3, 2)

a = make_array_by_shape(shape)

for s in [(4, 3, 2), (1, 3, 2), (3, 2), (2,), (4, 3), (4, 2, 3)]:
    b = make_array_by_shape(s, inital=10)
    print('---')
    try:
        t = a + b
        print('* shapes {} and {} can be evaluated, '
              'and answer shape is {}'.format(a.shape, b.shape, t.shape))
    except Exception as e:
        print('* E: {}'.format(e))

24
24
---
* shapes (4, 3, 2) and (4, 3, 2) can be evaluated, and answer shape is (4, 3, 2)
6
---
* shapes (4, 3, 2) and (1, 3, 2) can be evaluated, and answer shape is (4, 3, 2)
6
---
* shapes (4, 3, 2) and (3, 2) can be evaluated, and answer shape is (4, 3, 2)
2
---
* shapes (4, 3, 2) and (2,) can be evaluated, and answer shape is (4, 3, 2)
12
---
* E: operands could not be broadcast together with shapes (4,3,2) (4,3) 
24
---
* E: operands could not be broadcast together with shapes (4,3,2) (4,2,3) 


### 3. Dot product

In [12]:
from itertools import repeat

shape = (4, 3, 2)
a = make_array_by_shape(shape)
print('* when a is:{}'.format(ndarray_to_str(a)))

for s in [(2,), (2, 3), (5, 2, 3), (3,), (3, 4)]:
    b = make_array_by_shape(s, inital=10)
    try:
        t = np.dot(a, b)
        print('\n* if b is:{}\n  then "np.dot(a, b)" is:{}'.format(ndarray_to_str(b), ndarray_to_str(t)))
    except Exception as e:
        print('* E: {}'.format(e))

24
* when a is:
  [[[ 1  2]
    [ 3  4]
    [ 5  6]]
  
   [[ 7  8]
    [ 9 10]
    [11 12]]
  
   [[13 14]
    [15 16]
    [17 18]]
  
   [[19 20]
    [21 22]
    [23 24]]] (shape=(4, 3, 2), dtype=int64)
2

* if b is:
  [10 11] (shape=(2,), dtype=int64)
  then "np.dot(a, b)" is:
  [[ 32  74 116]
   [158 200 242]
   [284 326 368]
   [410 452 494]] (shape=(4, 3), dtype=int64)
6

* if b is:
  [[10 11 12]
   [13 14 15]] (shape=(2, 3), dtype=int64)
  then "np.dot(a, b)" is:
  [[[ 36  39  42]
    [ 82  89  96]
    [128 139 150]]
  
   [[174 189 204]
    [220 239 258]
    [266 289 312]]
  
   [[312 339 366]
    [358 389 420]
    [404 439 474]]
  
   [[450 489 528]
    [496 539 582]
    [542 589 636]]] (shape=(4, 3, 3), dtype=int64)
30

* if b is:
  [[[10 11 12]
    [13 14 15]]
  
   [[16 17 18]
    [19 20 21]]
  
   [[22 23 24]
    [25 26 27]]
  
   [[28 29 30]
    [31 32 33]]
  
   [[34 35 36]
    [37 38 39]]] (shape=(5, 2, 3), dtype=int64)
  then "np.dot(a, b)" is:
  [[[[  36   39   42]
  