# 转置

In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals
import numpy as np

def ndarray_to_str(t: np.ndarray):
    s = '\n{} (shape={}, dtype={})'.format(t, t.shape, t.dtype)
    s = s.replace('\n', '\n\t')
    return s

## T Transpose

- T Transpose 即轴对称转置，轴对称转置即将张量的行和列交换，相当于将张量旋转了 90°
- 假设`a`是`ndarray`，则`a.T`为其转置

- 张量 $A_{(2, 3)}$ 转置后变为 $A'_{(3, 2)}$，其中：
    - $ A[0, 0]=>A'[0, 0] $
    - $ A[0, 1]=>A'[1, 0] $
    - $ A[0, 2]=>A'[2, 0] $
    - $ A[1, 0]=>A'[0, 1] $
    - $ A[1, 1]=>A'[1, 1] $
    - $ A[1, 2]=>A'[2, 1] $
    
```
[[1 2 3]     [[1 4]
 [4 5 6]] =>  [2 5]
              [3 6]]
```

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('* when array "a" is:{}'.format(ndarray_to_str(a)))

t = a.T
print('* then "a.T" is:{}'.format(ndarray_to_str(t)))

a = np.array([[1, 2], [3, 4], [5, 6]])
print('\n* when "a" is:{}'.format(ndarray_to_str(a)))

t = a.T
print('* then "a.T" is:{}'.format(ndarray_to_str(t)))

- 张量 $A_{(1, 2, 3)}$ 转置后变为 $A'_{(3, 2, 1)}$，其中：
    - $ A[0, 0, 0]=>A'[0, 0, 0] $
    - $ A[0, 0, 1]=>A'[1, 0, 0] $
    - $ A[0, 0, 2]=>A'[2, 0, 0] $
    - $ A[0, 1, 0]=>A'[0, 1, 0] $
    - $ A[0, 1, 1]=>A'[1, 1, 0] $
    - $ A[0, 1, 2]=>A'[2, 1, 0] $
    - ...
    
```
[[[11 12 13]         [[[11]
  [14, 15, 16]]]  =>   [14]]
                      [[12]
                       [15]]
                      [[13]
                       [16]]]
```

In [ ]:
a = np.array([[[11, 12, 13], [14, 15, 16]]])
print('* when array "a" is:{}'.format(ndarray_to_str(a)))

t = a.T
print('* then "a.T" is:{}'.format(ndarray_to_str(t)))

## 任意轴转置

- `np.transpose`函数可以基于任意轴进行转置
    - `np.transpose(a)`与`np.transpose(a, (1, 0))`相当于轴对称转置
    - `np.transpose(a, (1, 2, 0))`相当于把 $A_{(x,y,z)}$ 集合转置为 $A'_{(y,z,x)}$

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('* when array "a" is:{}'.format(ndarray_to_str(a)))

t = np.transpose(a)
print('* then "np.transpose(a)" is:{}'.format(ndarray_to_str(t)))

t = np.transpose(a, (1, 0))
print('* and "np.transpose(a, (1, 0))" is:{}'.format(ndarray_to_str(t)))

a = np.reshape(np.arange(1, 25), (4, 3, 2))
print('\n* when array "a" is:{}'.format(ndarray_to_str(a)))

t = np.transpose(a, (1, 2, 0))
print('* then "np.transpose(a, (1, 2, 0))" is:{}'.format(ndarray_to_str(t)))