# 基础

In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals
import numpy as np

def ndarray_to_str(t: np.ndarray):
    s = '\n{} (shape={}, dtype={})'.format(t, t.shape, t.dtype)
    s = s.replace('\n', '\n\t')
    return s

## 基本运算

### 加法

- $m+n$

In [ ]:
a = 10
b = 0.1
r = np.add(a, b)
print('* when a={}, b={}, "np.add(a, b)" is {}'.format(a, b, r))

- $T(x, y) + n$

In [ ]:
a = [[1, 2, 3], [4, 5, 6]]
b = 0.1
r = np.add(a, b)
print('* when a={}, b={}, "np.add(a, b)" is {}'.format(a, b, ndarray_to_str(r)))

- $T_1(x_1, y_1) + T_2(x_2)$

In [ ]:
a = [[1, 2, 3], [4, 5, 6]]
b = [0.1, 0.2, 0.3]
r = np.add(a, b)
print('* when a={}, b={}, "np.add(a, b)" is {}'.format(a, b, ndarray_to_str(r)))

- $T_1(x_1, y_1) + T_2(x_2, y_2)$

In [ ]:
a = [[1, 2, 3], [4, 5, 6]]
b = [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]
r = np.add(a, b)
print('* when a={}, b={}, "np.add(a, b)" is {}'.format(a, b, ndarray_to_str(r)))

- 加号运算符重载
    - numpy 重载了`+`运算符，两个`np.ndarray`类型的对象相加，可以直接使用`+`，等同于`np.add`函数

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
r = a + b
print('* when "a" is: {}\n  and "b" is: {}\n  then "np.add(a, b)" is: {}'.format(ndarray_to_str(a), ndarray_to_str(b), ndarray_to_str(r)))

- 如果两个`ndarray`对象形状

In [10]:
from functools import reduce

shapes = [(3, 2)]

def make_array_by_shape(shape):
    m = reduce(lambda x, y: x * y, shape)
    return np.reshape(np.arange(1, m + 1), shape)

s = make_array_by_shape(shapes[0])
print(s)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
a = np.array(np.arange(1, 13).reshape((2, 3, 2)))
print(a)
b = np.array(np.arange(6).reshape((2, 3, 1)))
print(b)

r = np.c_[a, b]
print(r)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
[[[ 1  2  0]
  [ 3  4  1]
  [ 5  6  2]]

 [[ 7  8  3]
  [ 9 10  4]
  [11 12  5]]]
