# Basic of numpy

In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals
import numpy as np

def ndarray_to_str(t: np.ndarray):
    s = '\n{} (shape={}, dtype={})'.format(t, t.shape, t.dtype)
    s = s.replace('\n', '\n\t')
    return s

## Calculate

### Add

- $m+n$

In [ ]:
a = 10
b = 0.1
r = np.add(a, b)
print('* when a={}, b={}, "np.add(a, b)" is {}'.format(a, b, r))

- $T(x, y) + n$

In [ ]:
a = [[1, 2, 3], [4, 5, 6]]
b = 0.1
r = np.add(a, b)
print('* when a={}, b={}, "np.add(a, b)" is {}'.format(a, b, ndarray_to_str(r)))

- $T_1(x_1, y_1) + T_2(x_2)$

In [ ]:
a = [[1, 2, 3], [4, 5, 6]]
b = [0.1, 0.2, 0.3]
r = np.add(a, b)
print('* when a={}, b={}, "np.add(a, b)" is {}'.format(a, b, ndarray_to_str(r)))

- $T_1(x_1, y_1) + T_2(x_2, y_2)$

In [ ]:
a = [[1, 2, 3], [4, 5, 6]]
b = [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]
r = np.add(a, b)
print('* when a={}, b={}, "np.add(a, b)" is {}'.format(a, b, ndarray_to_str(r)))

- Operator override

In [42]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
r = a + b
print('* when "a" is: {}\n  and "b" is: {}\n  then "np.add(a, b)" is: {}'.format(ndarray_to_str(a), ndarray_to_str(b), ndarray_to_str(r)))

* when "a" is: 
	[[1 2 3]
	 [4 5 6]] (shape=(2, 3), dtype=int64)
  and "b" is: 
	[[0.1 0.2 0.3]
	 [0.4 0.5 0.6]] (shape=(2, 3), dtype=float64)
  then "np.add(a, b)" is: 
	[[1.1 2.2 3.3]
	 [4.4 5.5 6.6]] (shape=(2, 3), dtype=float64)


- Wrong shapes of two addtions

In [ ]:
a = [[1, 2, 3], [4, 5, 6]]
b = [0.1, 0.2, 0.3, 0.4]
try:
    np.add(a, b)
except Exception as err:
    print('* error caused: {}'.format(err))


a = [[1, 2, 3], [4, 5, 6]]
b = [[0.1, 0.2], [0.4, 0.5]]
try:
    np.add(a, b)
except Exception as err:
    print('* error caused: {}'.format(err))

In [61]:
a = np.array(np.arange(1, 13).reshape((2, 3, 2)))
print(a)
b = np.array(np.arange(6).reshape((2, 3, 1)))
print(b)

r = np.c_[a, b]
print(r)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
[[[ 1  2  0]
  [ 3  4  1]
  [ 5  6  2]]

 [[ 7  8  3]
  [ 9 10  4]
  [11 12  5]]]
