# 转置

In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals
import numpy as np

def ndarray_to_str(t: np.ndarray):
    s = '\n{} (shape={}, dtype={})'.format(t, t.shape, t.dtype)
    s = s.replace('\n', '\n\t')
    return s

## T Transpose

- T Transpose 即轴对称转置，轴对称转置即将张量的行和列交换，相当于将张量旋转了 90°
- 假设`a`是`ndarray`，则`a.T`为其转置

- 张量 $A_{(2, 3)}$ 转置后变为 $A'_{(3, 2)}$，其中：
    - $ A[0, 0]=>A'[0, 0] $
    - $ A[0, 1]=>A'[1, 0] $
    - $ A[0, 2]=>A'[2, 0] $
    - $ A[1, 0]=>A'[0, 1] $
    - $ A[1, 1]=>A'[1, 1] $
    - $ A[1, 2]=>A'[2, 1] $
    
```
[[1 2 3]     [[1 4]
 [4 5 6]] =>  [2 5]
              [3 6]]
```

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('* when array "a" is:{}'.format(ndarray_to_str(a)))

t = a.T
print('* then "a.T" is:{}'.format(ndarray_to_str(t)))

a = np.array([[1, 2], [3, 4], [5, 6]])
print('\n* when "a" is:{}'.format(ndarray_to_str(a)))

t = a.T
print('* then "a.T" is:{}'.format(ndarray_to_str(t)))

* when array "a" is:
	[[1 2 3]
	 [4 5 6]] (shape=(2, 3), dtype=int64)
* then "a.T" is:
	[[1 4]
	 [2 5]
	 [3 6]] (shape=(3, 2), dtype=int64)

* when "a" is:
	[[1 2]
	 [3 4]
	 [5 6]] (shape=(3, 2), dtype=int64)
* then "a.T" is:
	[[1 3 5]
	 [2 4 6]] (shape=(2, 3), dtype=int64)


- 张量 $A_{(1, 2, 3)}$ 转置后变为 $A'_{(3, 2, 1)}$，其中：
    - $ A[0, 0, 0]=>A'[0, 0, 0] $
    - $ A[0, 0, 1]=>A'[1, 0, 0] $
    - $ A[0, 0, 2]=>A'[2, 0, 0] $
    - $ A[0, 1, 0]=>A'[0, 1, 0] $
    - $ A[0, 1, 1]=>A'[1, 1, 0] $
    - $ A[0, 1, 2]=>A'[2, 1, 0] $
    - ...
    
```
[[[11 12 13]         [[[11]
  [14, 15, 16]]]  =>   [14]]
                      [[12]
                       [15]]
                      [[13]
                       [16]]]
```

In [26]:
a = np.array([[[11, 12, 13], [14, 15, 16]]])
print('* when array "a" is:{}'.format(ndarray_to_str(a)))

t = a.T
print('* then "a.T" is:{}'.format(ndarray_to_str(t)))

* when array "a" is:
	[[[11 12 13]
	  [14 15 16]]] (shape=(1, 2, 3), dtype=int64)
* then "a.T" is:
	[[[11]
	  [14]]
	
	 [[12]
	  [15]]
	
	 [[13]
	  [16]]] (shape=(3, 2, 1), dtype=int64)


In [29]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('* when array "a" is:{}'.format(ndarray_to_str(a)))

t = np.transpose(a)
print('* then "np.transpose(a)" is:{}'.format(ndarray_to_str(t)))

t = np.transpose(a, (1, 0))
print('* and "np.transpose(a, (1, 0))" is:{}'.format(ndarray_to_str(t)))

a = np.reshape(np.arange(1, 25), (4, 3, 2))
print('\n* when array "a" is:{}'.format(ndarray_to_str(a)))

t = np.transpose(a, (1, 2, 0))
print('* then "np.transpose(a, (1, 2, 0))" is:{}'.format(ndarray_to_str(t)))

* when array "a" is:
	[[1 2 3]
	 [4 5 6]] (shape=(2, 3), dtype=int64)
* then "np.transpose(a)" is:
	[[1 4]
	 [2 5]
	 [3 6]] (shape=(3, 2), dtype=int64)
* and "np.transpose(a, (1, 0))" is:
	[[1 4]
	 [2 5]
	 [3 6]] (shape=(3, 2), dtype=int64)

* when array "a" is:
	[[[ 1  2]
	  [ 3  4]
	  [ 5  6]]
	
	 [[ 7  8]
	  [ 9 10]
	  [11 12]]
	
	 [[13 14]
	  [15 16]
	  [17 18]]
	
	 [[19 20]
	  [21 22]
	  [23 24]]] (shape=(4, 3, 2), dtype=int64)
* then "np.transpose(a, (1, 2, 0))" is:
	[[[ 1  7 13 19]
	  [ 2  8 14 20]]
	
	 [[ 3  9 15 21]
	  [ 4 10 16 22]]
	
	 [[ 5 11 17 23]
	  [ 6 12 18 24]]] (shape=(3, 2, 4), dtype=int64)
