# 使用 Tensorflow 定义张量

In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf
import numpy as np


def tensor_to_str(vt):
    s = '\n{} (shape={}, type={})'.format(vt, vt.shape, vt.dtype)
    return '{}'.format(s.replace('\n', '\n\t'))

## 定义常量张量

### 整型常量张量

In [ ]:
t = tf.constant(value=1)
print('* "tf.constant(value=1)" is:{}'.format(tensor_to_str(t)))

### 实型常量张量

In [ ]:
t = tf.constant(value=1.)
print('* "tf.constant(value=1.)" is:{}'.format(tensor_to_str(t)))

t = tf.constant(value=2., dtype=tf.float64)  # 创建的同时指定数据类型
print('* "tf.constant(value=2., dtype=tf.double)" is:{}'.format(tensor_to_str(t)))

### 矩阵常量张量

In [ ]:
d = [[1., 2., 3.], [4., 5., 6.]]
t = tf.constant(value=d)  # 通过 list 对象创建张量
print('* when d={}, "tf.constant(value=d)" is:{}'.format(d, tensor_to_str(t)))

## 张量初始化

### 用现有数据初始化

In [ ]:
d = [[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]]
t = tf.convert_to_tensor(value=d)
print('* when d={}, "tf.constant(value=d)" is:{}'.format(d, tensor_to_str(t)))

d = np.ones(shape=(2, 3))
t = tf.convert_to_tensor(value=d)
print('\n* when d is {}, \n"tf.constant(value=d)" is:{}'.format(tensor_to_str(d), tensor_to_str(t)))

### 用 0 或 1 初始化

In [ ]:
t = tf.zeros(shape=(2, 3, 3))
print('* "tf.zeros(shape=(2, 3, 3))" is:{}'.format(tensor_to_str(t)))

t = tf.ones(shape=(2, 3))
print('\n* "tf.ones(shape=(2, 3))" is:{}'.format(tensor_to_str(t)))

### 用它其数据初始化

In [ ]:
t = tf.fill(dims=(2, 3), value=10.)
print('* "tf.fill(dims=(2, 3), value=10.)" is:{}'.format(tensor_to_str(t)))

### 用随机集合初始化

- `tf.random.normal`在一个标准方差内取随机值，即`[mean - stddev, mean + stddev]`
- `tf.random.truncated_normal`在两个标准方差内取随机值，即`[mean - 2(stddev), mean + 2(stddev)]`
- `tf.random.uniform`求在`minval`到`maxval`之间均匀分布的随机值

In [ ]:
t = tf.random.normal(shape=(2, 3), mean=1, stddev=1)
print('* "tf.random.normal(shape=(2, 3), mean=1, stddev=1)" is:{}'.format(tensor_to_str(t)))

t = tf.random.truncated_normal(shape=(2, 3), mean=1, stddev=1)
print('\n* "tf.random.truncated_normal(shape=(2, 3), mean=1, stddev=1)" is:{}'.format(tensor_to_str(t)))

t = tf.random.uniform(shape=(2, 3), minval=1., maxval=2.)  # 在1~2之间均匀分布
print('\n* "tf.random.uniform(shape=(2, 3), minval=1., maxval=2.)" is:{}'.format(tensor_to_str(t)))

### 用现有张量的形状初始化

In [ ]:
t = tf.convert_to_tensor(np.arange(24).reshape((2, 3, 4)))
print('* when t is:{}'.format(tensor_to_str(t)))

t_ = tf.zeros_like(t)
print('\n* then "tf.zeros_like(t)" is:{}'.format(tensor_to_str(t_)))

t_ = tf.ones_like(t)
print('\n* then "tf.ones_like(t)" is:{}'.format(tensor_to_str(t_)))

## 索引

### 单一索引

- 单一索引可以获取一个张量**指定维度**的数据，结果仍是一个张量。
- 索引运算符为`[]`，几个`[]`表示检索张量的第几个维度，例如：`t[0]`表示检索第一个维度的第0个数据
- 索引运算符有两种写法，`t[1, 0, 2]`和`t[1][0][2]`含义完全相同

In [ ]:
t = tf.convert_to_tensor(value=np.arange(80.).reshape(2, 2, 4, 5))
print('* when tensor t is:{}'.format(tensor_to_str(t)))

t_ = t[0]
print('\n* then t[0] is:{}'.format(tensor_to_str(t_)))

t_ = t[0, 1]
print('\n* and t[0, 1] is:{}'.format(tensor_to_str(t_)))

t_ = t[0, 1, 2]
print('\n* and t[0, 1, 2] is:{}'.format(tensor_to_str(t_)))

t_ = t[0, 1, 2, 3]
print('\n* and t[0, 1, 2, 3] is:{}'.format(tensor_to_str(t_)))

### 组合索引

In [54]:
t = tf.convert_to_tensor(np.arange(20.).reshape(4, 5))
print('* when tensor t is:{}'.format(tensor_to_str(t)))

t_ = tf.gather(params=t, axis=0, indices=[0, 2, 3])  # 维度 0, 表示取索引为 0, 2, 3 的行
print('\n* then t[[0, 2, 3]] is:{}'.format(tensor_to_str(t_)))

t_ = tf.gather(params=t_, axis=1, indices=[0, 2, 3])  # 维度 1, 表示取索引为 0, 2, 3 的列
print('\n* and t[[0, 2, 3]][..., [0, 2, 3]] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = tf.gather_nd(params=t, indices=[[1, 3], [2, 4]])  # 取第 1 行的第 3 列以及第 2 行的第 4 列
"""
对于 numpy，t[[1, 2], [3, 4]] 表示，第一维取 1, 2，即第 1 行和第 2 行，第二维取 3, 4，即在之前的结果上取第 3 列和第 4 列
"""
print('\n* and t[[1, 2], [3, 4]] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

* when tensor t is:
	[[ 0.  1.  2.  3.  4.]
	 [ 5.  6.  7.  8.  9.]
	 [10. 11. 12. 13. 14.]
	 [15. 16. 17. 18. 19.]] (shape=(4, 5), type=<dtype: 'float64'>)

* then t[[0, 2, 3]] is:
	[[ 0.  1.  2.  3.  4.]
	 [10. 11. 12. 13. 14.]
	 [15. 16. 17. 18. 19.]] (shape=(3, 5), type=<dtype: 'float64'>)

* and t[[0, 2, 3]][..., [0, 2, 3]] is:
[[ 0.  2.  3.]
 [10. 12. 13.]
 [15. 17. 18.]] (shape=(3, 3), type=<dtype: 'float64'>)

* and t[[1, 2], [3, 4]] is:
[ 8. 14.] (shape=(2,), type=<dtype: 'float64'>)
