In [ ]:
"""
常量张量
"""

import tensorflow as tf
import numpy as np

t = tf.constant(value=1)  # 创建一个整型张量
print('* "tf.constant(value=1)" is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))

t = tf.constant(value=1.)  # 创建一个浮点型张量
print('\n* "tf.constant(value=1.)" is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))

t = tf.constant(value=2., dtype=tf.double)  # 创建的同时指定数据类型
print('\n* "tf.constant(value=2., dtype=tf.double)" is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))

d = [[1., 2., 3.], [4., 5., 6.]]
t = tf.constant(value=d)  # 通过 list 对象创建张量
print('\n* when d={}, "tf.constant(value=d)" is:\n{} (shape={}, type={})'.format(d, t, t.shape, t.dtype))

In [10]:
"""
张量初始化
"""

import tensorflow as tf
import numpy as np


"""
用现有数据初始化
"""
d = [[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]]
t = tf.convert_to_tensor(value=d)
print('* when d={} "tf.convert_to_tensor(value=d)" is:\n{} (shape={}, type={})'.format(d, t, t.shape, t.dtype))

d = np.ones(shape=(2, 3))
t = tf.convert_to_tensor(value=d)
print('\n* when d={} "tf.convert_to_tensor(value=d)" is:\n{} (shape={}, type={})'.format(d, t, t.shape, t.dtype))


"""
用 0 或 1 初始化
"""
t = tf.zeros(shape=(2, 3, 3))
print('\n* "tf.zeros(shape=(2, 3, 3))" is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))

t = tf.ones(shape=(2, 3))
print('\n* "tf.ones(shape=(2, 3))" is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))


"""
用它其数据初始化
"""
t = tf.fill(dims=(2, 3), value=10.)
print('\n* "tf.fill(dims=(2, 3), value=10.)" is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))


"""
用随机集合初始化
"""
t = tf.random.normal(shape=(2, 3), mean=1, stddev=1)  # 随即初始化，均值为 1，方差为 1
print('\n* "tf.random.normal(shape=(2, 3), mean=1, stddev=1)" is:\n'
      '{} (shape={}, type={})'.format(t, t.shape, t.dtype))

t = tf.random.truncated_normal(shape=(2, 3), mean=1, stddev=1)  # 随即初始化，均值为 1，方差为 1
# 取值范围在两个标准差范围内, 即 [mean - 2 stddev, mean + 2 stddev]
print('\n* "tf.random.truncated_normal(shape=(2, 3), mean=1, stddev=1)" is:\n'
      '{} (shape={}, type={})'.format(t, t.shape, t.dtype))

t = tf.random.uniform(shape=(2, 3), minval=1., maxval=2.)  # 在1~2之间均匀分布
print('\n* "tf.random.uniform(shape=(2, 3), minval=1., maxval=2.)" is:\n'
      '{} (shape={}, type={})'.format(t, t.shape, t.dtype))


"""
用现有的结构初始化
"""
t = tf.convert_to_tensor(np.arange(24).reshape((2, 3, 4)))
print('\n* when t is is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))

t_ = tf.ones_like(t)
print('\n* then "tf.ones_like(t) is:\n{} (shape={}, type={})"'.format(t_, t_.shape, t_.dtype))

* when d=[[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]] "tf.convert_to_tensor(value=d)" is:
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]] (shape=(2, 2, 2), type=<dtype: 'float32'>)

* when d=[[1. 1. 1.]
 [1. 1. 1.]] "tf.convert_to_tensor(value=d)" is:
[[1. 1. 1.]
 [1. 1. 1.]] (shape=(2, 3), type=<dtype: 'float64'>)

* "tf.zeros(shape=(2, 3, 3))" is:
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] (shape=(2, 3, 3), type=<dtype: 'float32'>)

* "tf.ones(shape=(2, 3))" is:
[[1. 1. 1.]
 [1. 1. 1.]] (shape=(2, 3), type=<dtype: 'float32'>)

* "tf.fill(dims=(2, 3), value=10.)" is:
[[10. 10. 10.]
 [10. 10. 10.]] (shape=(2, 3), type=<dtype: 'float32'>)

* "tf.random.normal(shape=(2, 3), mean=1, stddev=1)" is:
[[2.2908459 0.8290651 0.9700937]
 [1.3136652 0.8602052 0.6343925]] (shape=(2, 3), type=<dtype: 'float32'>)

* "tf.random.truncated_normal(shape=(2, 3), mean=1, stddev=1)" is:
[[0.5375703 1.3820164 1.1599529]
 [0.8157551 1.199599  2.1766014]] (shape=(2, 

In [ ]:
"""
Index
"""

import tensorflow as tf
import numpy as np

t = tf.convert_to_tensor(value=np.arange(80.).reshape(2, 2, 4, 5))
print('* when tensor t is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))

t_ = t[0]
print('\n* then t[0] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = t[0, 1]
print('\n* and t[0, 1] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = t[0, 1, 2]
print('\n* and t[0, 1, 2] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = t[0, 1, 2, 3]
print('\n* and t[0, 1, 2, 3] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

In [ ]:
"""
Nested index
"""

import tensorflow as tf
import numpy as np

t = tf.convert_to_tensor(np.arange(20.).reshape(4, 5))
print('* when tensor t is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))

t_ = tf.gather(params=t, axis=0, indices=[0, 2, 3])  # 维度 0, 表示取索引为 0, 2, 3 的行
print('\n* then t[[0, 2, 3]] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = tf.gather(params=t_, axis=1, indices=[0, 2, 3])  # 维度 1, 表示取索引为 0, 2, 3 的列
print('\n* and t[[0, 2, 3]][..., [0, 2, 3]] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = tf.gather_nd(params=t, indices=[[1, 3], [2, 4]])  # 取第 1 行的第 3 列以及第 2 行的第 4 列
"""
对于 numpy，t[[1, 2], [3, 4]] 表示，第一维取 1, 2，即第 1 行和第 2 行，第二维取 3, 4，即在之前的结果上取第 3 列和第 4 列
"""
print('\n* and t[[1, 2], [3, 4]] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

In [ ]:
"""
Slice
"""

import tensorflow as tf
import numpy as np

t = tf.convert_to_tensor(value=np.arange(80.).reshape(2, 2, 4, 5))
print('* when tensor t is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))

t_ = t[:, 1:]
print('\n* then t[:, 1] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = t[:, 1:, 2:4]
print('\n* and t[:, 1:, 2:4] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = t[:, 1:, 2:4, 3]
print('\n* and t[:, 1:, 3] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = t[:, 1:, 2:4, 1:3]
print('\n* and t[:, 1:, 1:3] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = t[..., 1:3]  # t_ = t[:, :, :, 1:3]
print('\n* and t[..., 1:3] is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

In [ ]:
"""
Find by condition
"""

import tensorflow as tf


t = tf.random.uniform(shape=(3, 3), minval=-10, maxval=10, dtype=tf.int32)
print('* when tensor t is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))

mask = t < 0
print('\n* then t < 0 is:\n{} (shape={}, type={})'.format(mask, mask.shape, mask.dtype))

t_ = tf.boolean_mask(tensor=t, mask=mask)
print('\n* and "tf.boolean_mask(tensor=t, mask=t < 0)" is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

indices = tf.where(condition=t < 0)
print('\n* and "tf.where(condition=t < 0)" is:\n{} (shape={}, type={})'.format(indices, indices.shape, indices.dtype))

t_ = tf.gather_nd(t, indices)
print('\n* and "tf.gather_nd(t, tf.where(t < 0))" is:\n{} (shape={}, type={})'.format(indices, t_, t_.shape, t_.dtype))

condition = tf.cast(tf.random.uniform([3, 3], minval=0, maxval=2, dtype=tf.int32), tf.bool)
print('\n* when condition is:\n{} (shape={}, type={})'.format(condition, condition.shape, condition.dtype))

t1 = tf.reshape(tensor=tf.range(1, 10), shape=(3, 3))
print('\n* and t1 is:\n{} (shape={}, type={})'.format(t1, t1.shape, t1.dtype))

t2 = tf.reshape(tensor=tf.range(-9, 0), shape=(3, 3))
print('\n* and t2 is:\n{} (shape={}, type={})'.format(t2, t2.shape, t2.dtype))

t_ = tf.where(condition, t1, t2)
print('\n* then "tf.where(condition, t1, t2)" is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

In [ ]:
"""
Reshape
"""

import tensorflow as tf
import numpy as np

t = tf.convert_to_tensor(np.arange(20.))
print('* when tensor t is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))

t_ = tf.reshape(t, (2, 10))
print('\n* then tf.reshape(t, (2, 10)) is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = tf.reshape(t, (2, 5, 2))
print('\n* then tf.reshape(t, (2, 5, 2)) is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

In [ ]:
"""
Transpose
"""

import tensorflow as tf
import numpy as np

t = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], ])  # source matrix, shape is (2, 3)
print('* when tensor t is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))

t_ = tf.transpose(t)  # default transpose, perm is (1, 0), means from shape (2, 3) to shape (3, 2)
print('\n* then tf.transpose(t) is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = tf.transpose(t, perm=(1, 0))  # perm is (1, 0), means from shape (2, 3) to shape (3, 2)
print('\n* then tf.transpose(t, perm=(1, 0)) is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t = tf.constant(np.arange(24).reshape((2, 3, 4)))  # source matrix, shape is (2, 3, 4)
print('\n* when tensor t is:\n{} (shape={}, type={})'.format(t, t.shape, t.dtype))

t_ = tf.transpose(t)  # default transpose, perm is (2, 1, 0), means from shape (2, 3, 4) to shape (4, 3, 2)
print('\n* then tf.transpose(t) is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = tf.transpose(t, perm=(2, 1, 0))  # perm is (2, 1, 0), means from shape (2, 3, 4) to shape (4, 3, 2)
print('\n* then tf.transpose(t, perm=(1, 2, 0)) is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = tf.transpose(t, perm=(0, 2, 1))  # perm is (0, 2, 1), means from shape (2, 3, 4) to shape (2, 4, 3)
print('\n* then tf.transpose(t, perm=(2, 1, 0)) is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

t_ = tf.transpose(t, perm=(2, 0, 1)) # perm is (2, 0, 1), means from shape (2, 3, 4) to shape (4, 2, 3)
print('\n* then tf.transpose(t, perm=(2, 1, 0)) is:\n{} (shape={}, type={})'.format(t_, t_.shape, t_.dtype))

In [ ]:
import tensorflow as tf

@tf.function
def add(h, W):
    return tf.add(h, W)


r = add('Hello', ' World')
print('* result type is "{}"'.format(r.__class__.__name__))
print('* result value is "{}"'.format(r.numpy()))

In [ ]:
import tensorflow as tf

def linear_layer(x):
    return 2 * x + 1

@tf.function
def deep_net(x):
    return tf.nn.relu(linear_layer(x))

r = deep_net(tf.constant((1, -2, 3)))
print('* result is {}'.format(r))

In [ ]:
import tensorflow as tf

@tf.function
def simple_matmul(x, y):
    return tf.matmul(x, y)

@tf.function
def simple_nn_layer(x, y):
    return tf.nn.relu(tf.matmul(x, y))


x = tf.random.uniform((3, 3), minval=-0.5, maxval=0.5)
print('variable x is:\n{}'.format(x))

y = tf.random.uniform((3, 3))
print('variable y is:\n{}'.format(y))

xy = simple_matmul(x, y)
print('x · y is:\n{}'.format(xy))

relu = simple_nn_layer(x, y)
print('relu(x · y) is:\n{}'.format(relu))  # relu