In [76]:
import tensorflow as tf

@tf.function
def add(h, W):
    return tf.add(h, W)


r = add('Hello', ' World')
print('* result type is "{}"'.format(r.__class__.__name__))
print('* result value is "{}"'.format(r.numpy()))

* result type is "EagerTensor"
* result value is "b'Hello World'"


In [77]:
import tensorflow as tf

def linear_layer(x):
    return 2 * x + 1

@tf.function
def deep_net(x):
    return tf.nn.relu(linear_layer(x))

r = deep_net(tf.constant((1, -2, 3)))
print('* result is {}'.format(r))

* result is [3 0 7]


In [78]:
import tensorflow as tf

@tf.function
def simple_matmul(x, y):
    return tf.matmul(x, y)

@tf.function
def simple_nn_layer(x, y):
    return tf.nn.relu(tf.matmul(x, y))


x = tf.random.uniform((3, 3), minval=-0.5, maxval=0.5)
print('variable x is:\n{}'.format(x))

y = tf.random.uniform((3, 3))
print('variable y is:\n{}'.format(y))

xy = simple_matmul(x, y)
print('x · y is:\n{}'.format(xy))

relu = simple_nn_layer(x, y)
print('relu(x · y) is:\n{}'.format(relu))  # relu

variable x is:
[[ 0.41979003  0.02658522 -0.03694689]
 [-0.4899968  -0.26153696 -0.23578537]
 [-0.46489942  0.06253743  0.04813612]]
variable y is:
[[0.0128175  0.9500203  0.63705134]
 [0.54777133 0.5567939  0.07118535]
 [0.91261613 0.9283582  0.3724078 ]]
x · y is:
[[-0.01377505  0.3793116   0.25556096]
 [-0.36472452 -0.8300224  -0.418579  ]
 [ 0.07222716 -0.36215585 -0.27378678]]
relu(x · y) is:
[[0.         0.3793116  0.25556096]
 [0.         0.         0.        ]
 [0.07222716 0.         0.        ]]
